# DZ19 — Статистичне дослідження швидкостей птахів

У цьому завданні ми працюємо з даними про **середні швидкості птахів**. Таблиця зберігається у файлі `birds.csv` і має стовпці:
- `SPECIES` — назва птаха;
- `AVR_KMH` — середня швидкість польоту в км/год.

Далі крок за кроком виконаємо статистичний аналіз по запитанням.

In [2]:
import pandas as pd

# Завантажуємо дані з файлу birds.csv
df = pd.read_csv('birds.csv', encoding='cp1251', sep=',')
df

    SPECIES  AVR_KMH
0    Лелека    40.00
1  Вівсянка    48.26
2     Сокіл    76.50
3   Колібрі    41.00
4   Пелікан    66.50
5    Папуга    44.00
6    Сорока    32.40
7      Сова    56.00

In [3]:
# Базова описова статистика для числових стовпців
df.describe()

         AVR_KMH
count   8.000000
mean   50.582500
std    14.820705
min    32.400000
25%    40.750000
50%    46.130000
75%    58.625000
max    76.500000

### Дослідження
- `import pandas as pd` — підключаємо `pandas` для роботи з табличками.
- `pd.read_csv('birds.csv', encoding='cp1251', sep=',')` зчитує CSV‑файл з кирилицею у датафрейм `df`.
- Вивід `df` показує всі види птахів (`SPECIES`) та їх середні швидкості `AVR_KMH`.
- Команда `df.describe()` одразу рахує основні статистики для всіх числових стовпців датафрейму:
  `count`, `mean`, `std`, мінімум, квартилі (25%, 50%, 75%) і максимум.
- У нашому випадку це стовпець `AVR_KMH`, тому з цієї таблиці ми можемо прямо взяти значення
  середнього (`mean`) та стандартного відхилення (`std`) для відповіді на перше запитання.

## 1. Чому дорівнює стандартне відхилення набору даних?
Нас цікавить, наскільки **розкидані** швидкості птахів навколо свого середнього значення.

In [4]:
# 1. Стандартне відхилення швидкостей (через describe)
stats = df['AVR_KMH'].describe()
mean_speed = stats['mean']
std_speed = stats['std']

print(f"Середня швидкість (mean): {mean_speed:.2f} км/год")
print(f"Стандартне відхилення (std): {std_speed:.2f} км/год")

stats

Середня швидкість (mean): 50.58 км/год
Стандартне відхилення (std): 14.82 км/год

count     8.000000
mean     50.582500
std      14.820705
min      32.400000
25%      40.750000
50%      46.130000
75%      58.625000
max      76.500000
Name: AVR_KMH, dtype: float64

### Дослідження
- Використовуємо `df['AVR_KMH'].describe()`, щоб одразу отримати всі ключові статистики по швидкостях.
- Зі словника `stats` беремо:
  - `stats['mean']` — середню швидкість,
  - `stats['std']` — стандартне відхилення.
- Виводимо ці значення окремо, а також показуємо сам `stats`, щоб бачити повну таблицю: count, min, quartiles, max.

## 2. Чи є серед отриманих даних викиди (outliers)?
Перевіримо це за правилом **IQR (інтерквартильний розмах)**.

In [5]:
# 2. Пошук викидів за допомогою IQR (через describe)
stats_iqr = df['AVR_KMH'].describe()
q1 = stats_iqr['25%']
q3 = stats_iqr['75%']
iqr = q3 - q1

lower_bound = q1 - 1.5 * iqr
upper_bound = q3 + 1.5 * iqr

print(f"Q1 = {q1:.2f} км/год")
print(f"Q3 = {q3:.2f} км/год")
print(f"IQR = {iqr:.2f} км/год")
print(f"Нижня межа (lower_bound) = {lower_bound:.2f} км/год")
print(f"Верхня межа (upper_bound) = {upper_bound:.2f} км/год")

outliers = df[(df['AVR_KMH'] < lower_bound) | (df['AVR_KMH'] > upper_bound)]
outliers

Q1 = 40.75 км/год
Q3 = 58.62 км/год
IQR = 17.88 км/год
Нижня межа (lower_bound) = 13.94 км/год
Верхня межа (upper_bound) = 85.44 км/год

Empty DataFrame
Columns: [SPECIES, AVR_KMH]
Index: []

### Дослідження
- `Q1` та `Q3` — це перший і третій квартилі: на них припадає 25% і 75% даних.
- `IQR = Q3 - Q1` — інтерквартильний розмах, основний робочий діапазон даних.
- Межі для пошуку викидів:
  - нижня: `Q1 - 1.5 * IQR`,
  - верхня: `Q3 + 1.5 * IQR`.
- Якщо швидкість птаха виходить за ці межі, він потрапляє в датафрейм `outliers` і вважається викидом.

## 3. Реалізуйте запит до датафрейму, щоб знайти найшвидшу пташку.

In [6]:
# 3. Найшвидша пташка
max_speed = df['AVR_KMH'].max()
fast_bird = df[df['AVR_KMH'] == max_speed]
fast_bird

  SPECIES  AVR_KMH
2   Сокіл     76.5

### Дослідження
- `max()` знаходить максимальну швидкість з усіх значень `AVR_KMH`.
- Потім ми відбираємо рядок(и), де `AVR_KMH` дорівнює `max_speed`, і бачимо назву найшвидшого птаха.

## 4. Як змінити запит, щоб отримати ТОП‑3 найшвидших птахів у датафреймі?

In [7]:
# 4. ТОП‑3 найшвидших птахів
top3_birds = df.sort_values('AVR_KMH', ascending=False).head(3)
top3_birds

   SPECIES  AVR_KMH
2    Сокіл     76.5
4  Пелікан     66.5
7     Сова     56.0

### Дослідження
- `sort_values('AVR_KMH', ascending=False)` сортує рядки за швидкістю від більшої до меншої.
- `head(3)` залишає лише перші три рядки — це ТОП‑3 найшвидших птахів.
- Такий самий прийом можна використати для будь-якого ТОП‑N.

## 5. Які птахи мають швидкість ближче до медіани, ніж до середнього значення?

In [8]:
# 5. Птахи, швидкість яких ближча до медіани, ніж до середнього
median_speed = df['AVR_KMH'].median()
mean_speed = df['AVR_KMH'].mean()

diff_to_median = (df['AVR_KMH'] - median_speed).abs()
diff_to_mean = (df['AVR_KMH'] - mean_speed).abs()

closer_to_median = df[diff_to_median < diff_to_mean]
closer_to_median

    SPECIES  AVR_KMH
0    Лелека    40.00
1  Вівсянка    48.26
3   Колібрі    41.00
5    Папуга    44.00
6    Сорока    32.40

### Дослідження
- Обчислюємо **медіану** і **середнє** значення швидкості.
- Для кожного рядка рахуємо, наскільки його швидкість відрізняється від медіани (`diff_to_median`) і від середнього (`diff_to_mean`).
- У вибірку потрапляють ті птахи, для яких `diff_to_median < diff_to_mean`, тобто вони ближчі саме до медіани.
- Такі види можна вважати типовими представниками нашої вибірки.

## 6. Як зміниться середня швидкість (MEAN) і стандартне відхилення (STD), якщо виключити найповільнішого і найшвидшого птаха?

In [9]:
# 6. Перерахунок mean і std без найповільнішого та найшвидшого птаха (через describe)
min_speed = df['AVR_KMH'].min()
max_speed = df['AVR_KMH'].max()

print(f"Найповільніший птах, км/год: {min_speed}")
print(f"Найшвидший птах, км/год: {max_speed}")

# Залишаємо тільки тих птахів, чиї швидкості строго між min та max
df_middle = df[(df['AVR_KMH'] > min_speed) & (df['AVR_KMH'] < max_speed)]

# Описова статистика для повного набору
stats_full = df['AVR_KMH'].describe()
mean_full = stats_full['mean']
std_full = stats_full['std']

# Описова статистика для набору без крайніх значень
stats_middle = df_middle['AVR_KMH'].describe()
mean_middle = stats_middle['mean']
std_middle = stats_middle['std']

print(f"Повний набір: mean = {mean_full:.2f}, std = {std_full:.2f}")
print(f"Без крайніх: mean = {mean_middle:.2f}, std = {std_middle:.2f}")

Найповільніший птах, км/год: 32.4
Найшвидший птах, км/год: 76.5
Повний набір: mean = 50.58, std = 14.82
Без крайніх: mean = 49.29, std = 10.25

### Дослідження
- Знаходимо мінімальну та максимальну швидкість (`min` і `max`).
- Створюємо датафрейм `df_middle`, де прибираємо ці крайні значення.
- Окремо рахуємо середню швидкість і стандартне відхилення:
  - для **повного набору** птахів;
  - для набору **без найповільнішого і найшвидшого**.
- Порівнюючи ці дві пари чисел, можна оцінити, наскільки сильно крайні значення впливають на статистику.

## Підсумок
- Завантажили дані з файлу `birds.csv` і подивилися базові характеристики.
- Обчислили стандартне відхилення та перевірили дані на викиди.
- Знайшли найшвидшу пташку та ТОП‑3 найшвидших видів.
- Визначили птахів, у яких швидкість ближча до медіани, ніж до середнього.
- Перерахували mean і std без найповільнішого та найшвидшого птаха і порівняли результати.